# SPDX-FileCopyrightText: 2022 Jonah Aragon <jonah@privacyguides.org>
#
# SPDX-License-Identifier: MIT

default: true
line-length: false
ul-indent:
  indent: 4
no-inline-html: false
code-block-style: false
no-hard-tabs: true
emphasis-style:
  style: "asterisk"
no-trailing-punctuation: false
no-duplicate-heading:
  siblings_only: true
