# SPDX-FileCopyrightText: 2023 Jonah Aragon <jonah@privacyguides.org>
#
# SPDX-License-Identifier: MIT OR CC-BY-SA-4.0

#checkov:skip=CKV_SECRET_6:obviously a variable name and not a secret
api_token_env: CROWDIN_PERSONAL_TOKEN
project_id: "509862"
"preserve_hierarchy": true
files:
  - source: "/docs/**/*.*"
    translation: "/i18n/%two_letters_code%/**/%file_name%.%file_extension%"
    skip_untranslated_files: false
  - source: "/includes/*.en.*"
    translation: "/includes/%file_name%.%two_letters_code%.%file_extension%"
    translation_replace:
      "en.": ""
    skip_untranslated_files: false
