#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files:
- source: "/docs/**/*.en.md"
  translation: "/docs/**/%file_name%.%two_letters_code%.md"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
- source: "/theme/overrides/*.en.html"
  translation: "/theme/overrides/%file_name%.%two_letters_code%.html"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved

#
# Integration configuration
#
"pull_request_title": "Crowdin translation updates"
"pull_request_labels": [
  "l10n"
]
