#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files:
- source: "/docs/**/*.en.md"
  translation: "/docs/**/%file_name%.%two_letters_code%.md"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
