version = 1

# Privacy Guides Paid Work - Em
[[annotations]]
path = [
    "*"
]
SPDX-FileCopyrightText = "Privacy Guides <https://magicgrants.org/funds/privacy_guides/>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileContributor = "Em <em@privacyguides.org>"
