# SPDX-FileCopyrightText: 2024 Jonah Aragon <jonah@privacyguides.org>
#
# SPDX-License-Identifier: MIT

name: 📦 Manual Test Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submodule:
    strategy:
      matrix:
        repo: [mkdocs-material-insiders, brand, i18n]
    uses: privacyguides/.github/.github/workflows/download-repo.yml@main
    with:
      repo: ${{ matrix.repo }}
    secrets:
      ACTIONS_SSH_KEY: ${{ secrets.ACTIONS_SSH_KEY }}

  build:
    needs: submodule
    strategy:
      matrix:
        lang: [en, fr, he]
        build: [build, offline]
      fail-fast: false
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      config: ${{ matrix.build }}
      ref: ${{ github.ref }}
      repo: ${{ github.repository }}
      lang: ${{ matrix.lang }}
      continue-on-error: true

  cleanup:
    if: ${{ always() }}
    needs: build
    uses: privacyguides/.github/.github/workflows/cleanup.yml@main
